name: schoolbus_bridge_driver
description: SchoolBus Bridge Flutter app for driver operations.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.3.1

flutter:
  uses-material-design: true
