-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alerts (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  trip_id text,
  student_id text,
  user_id text,
  title text NOT NULL,
  body text,
  alert_type USER-DEFINED NOT NULL,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  route_id text,
  CONSTRAINT alerts_pkey PRIMARY KEY (id),
  CONSTRAINT alerts_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT alerts_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT alerts_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT alerts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT alerts_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id)
);
CREATE TABLE public.attendance_events (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  trip_id text NOT NULL,
  student_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['boarded'::text, 'dropped'::text, 'no_show'::text, 'skipped'::text, 'manual_override'::text])),
  recorded_by text,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT attendance_events_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_events_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT attendance_events_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT attendance_events_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT attendance_events_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.users(id)
);
CREATE TABLE public.buses (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  plate text,
  capacity integer NOT NULL DEFAULT 50,
  vehicle_type text DEFAULT 'bus'::text CHECK (vehicle_type = ANY (ARRAY['bus'::text, 'van'::text, 'mini_bus'::text, 'other'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  vehicle_number text,
  driver_id text,
  route_id text,
  gps_device_id text,
  current_latitude double precision,
  current_longitude double precision,
  status USER-DEFINED DEFAULT 'idle'::transport_bus_status,
  CONSTRAINT buses_pkey PRIMARY KEY (id),
  CONSTRAINT buses_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT buses_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id),
  CONSTRAINT buses_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id)
);
CREATE TABLE public.drivers (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  user_id text,
  first_name text NOT NULL,
  last_name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  full_name text,
  phone_number text,
  email text,
  date_of_birth date,
  gender USER-DEFINED,
  address text,
  license_number text,
  license_type USER-DEFINED,
  license_expiry_date date,
  aadhar_number text,
  photo_url text,
  police_verification_status USER-DEFINED DEFAULT 'pending'::transport_police_verification_status,
  employee_id text,
  joining_date date,
  status USER-DEFINED DEFAULT 'active'::transport_employee_status,
  medical_certificate_expiry date,
  emergency_contact_name text,
  emergency_contact_phone text,
  assigned_bus_id text,
  current_latitude double precision,
  current_longitude double precision,
  is_online boolean NOT NULL DEFAULT false,
  last_active_at timestamp with time zone,
  CONSTRAINT drivers_pkey PRIMARY KEY (id),
  CONSTRAINT drivers_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT drivers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT drivers_assigned_bus_id_fkey FOREIGN KEY (assigned_bus_id) REFERENCES public.buses(id)
);
CREATE TABLE public.eta_updates (
  id text NOT NULL DEFAULT md5(((random())::text || (clock_timestamp())::text)),
  school_id text NOT NULL,
  trip_id text NOT NULL,
  trip_stop_id text,
  student_id text,
  reason text NOT NULL,
  eta_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT eta_updates_pkey PRIMARY KEY (id),
  CONSTRAINT eta_updates_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT eta_updates_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT eta_updates_trip_stop_id_fkey FOREIGN KEY (trip_stop_id) REFERENCES public.trip_stops(id),
  CONSTRAINT eta_updates_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.leave_requests (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  student_id text NOT NULL,
  requested_by_parent_id text NOT NULL,
  leave_date date NOT NULL,
  reason text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'cancelled'::text])),
  reviewed_by text,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT leave_requests_requested_by_parent_id_fkey FOREIGN KEY (requested_by_parent_id) REFERENCES public.users(id),
  CONSTRAINT leave_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id)
);
CREATE TABLE public.nightly_planner_runs (
  id text NOT NULL DEFAULT md5(((random())::text || (clock_timestamp())::text)),
  school_id text NOT NULL,
  run_date date NOT NULL,
  trigger_type text NOT NULL CHECK (trigger_type = ANY (ARRAY['manual'::text, 'automatic'::text])),
  status text NOT NULL CHECK (status = ANY (ARRAY['success'::text, 'failed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  error_code text,
  processed_trips integer NOT NULL DEFAULT 0,
  planned_trips integer NOT NULL DEFAULT 0,
  skipped_trips integer NOT NULL DEFAULT 0,
  error_message text,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  finished_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT nightly_planner_runs_pkey PRIMARY KEY (id),
  CONSTRAINT nightly_planner_runs_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.parent_password_reset_otps (
  id text NOT NULL DEFAULT md5(((random())::text || (clock_timestamp())::text)),
  parent_user_id text NOT NULL,
  auth_user_id text NOT NULL,
  email text NOT NULL,
  otp_hash text NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  attempts integer NOT NULL DEFAULT 0,
  consumed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT parent_password_reset_otps_pkey PRIMARY KEY (id),
  CONSTRAINT parent_password_reset_otps_parent_user_id_fkey FOREIGN KEY (parent_user_id) REFERENCES public.users(id)
);
CREATE TABLE public.parent_students (
  id text NOT NULL DEFAULT md5(((random())::text || (clock_timestamp())::text)),
  parent_id text NOT NULL,
  student_id text NOT NULL,
  relation USER-DEFINED,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT parent_students_pkey PRIMARY KEY (id),
  CONSTRAINT parent_students_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.parents(id),
  CONSTRAINT parent_students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.parents (
  id text NOT NULL,
  full_name text,
  phone_number text NOT NULL,
  email text,
  address text,
  relation USER-DEFINED,
  password_hash text,
  notification_preferences jsonb NOT NULL DEFAULT jsonb_build_object('sms', true, 'push', true, 'email', true),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT parents_pkey PRIMARY KEY (id),
  CONSTRAINT parents_id_fkey FOREIGN KEY (id) REFERENCES public.users(id)
);
CREATE TABLE public.route_plan_versions (
  id text NOT NULL DEFAULT md5(((random())::text || (clock_timestamp())::text)),
  school_id text NOT NULL,
  trip_id text NOT NULL,
  version integer NOT NULL,
  reason text NOT NULL,
  snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  route_engine_mode text,
  CONSTRAINT route_plan_versions_pkey PRIMARY KEY (id),
  CONSTRAINT route_plan_versions_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT route_plan_versions_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.routes (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  description text,
  direction text NOT NULL DEFAULT 'pickup'::text CHECK (direction = ANY (ARRAY['pickup'::text, 'drop'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  route_name text,
  route_code text,
  status USER-DEFINED DEFAULT 'active'::transport_route_status,
  CONSTRAINT routes_pkey PRIMARY KEY (id),
  CONSTRAINT routes_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.school_map_settings (
  id text NOT NULL DEFAULT md5(((random())::text || (clock_timestamp())::text)),
  school_id text NOT NULL UNIQUE,
  dispatch_start_time timestamp with time zone,
  no_show_wait_seconds integer NOT NULL DEFAULT 120,
  max_detour_minutes integer NOT NULL DEFAULT 15,
  dispatch_latitude double precision,
  dispatch_longitude double precision,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT school_map_settings_pkey PRIMARY KEY (id),
  CONSTRAINT school_map_settings_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.schools (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  address text,
  latitude double precision,
  longitude double precision,
  logo_url text,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT schools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stops (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  route_id text,
  address text,
  latitude double precision,
  longitude double precision,
  estimated_wait_seconds integer NOT NULL DEFAULT 120,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  stop_name text,
  sequence_order integer,
  CONSTRAINT stops_pkey PRIMARY KEY (id),
  CONSTRAINT stops_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT stops_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id)
);
CREATE TABLE public.student_guardians (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  student_id text NOT NULL,
  parent_id text NOT NULL,
  relation text NOT NULL DEFAULT 'parent'::text CHECK (relation = ANY (ARRAY['father'::text, 'mother'::text, 'guardian'::text, 'parent'::text, 'other'::text])),
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_guardians_pkey PRIMARY KEY (id),
  CONSTRAINT student_guardians_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_guardians_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.users(id)
);
CREATE TABLE public.student_transport_assignments (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  student_id text NOT NULL,
  route_id text,
  stop_id text,
  effective_from date NOT NULL DEFAULT CURRENT_DATE,
  effective_to date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_transport_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT student_transport_assignments_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT student_transport_assignments_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT student_transport_assignments_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id),
  CONSTRAINT student_transport_assignments_stop_id_fkey FOREIGN KEY (stop_id) REFERENCES public.stops(id)
);
CREATE TABLE public.students (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  first_name text NOT NULL,
  last_name text NOT NULL,
  grade text,
  section text,
  roll_number text,
  phone text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  geocode_status text DEFAULT 'pending'::text,
  place_id text,
  last_geocoded_at timestamp with time zone,
  geocode_error text,
  admission_number text,
  date_of_birth date,
  gender USER-DEFINED,
  photo_url text,
  class text,
  pickup_stop_id text,
  drop_stop_id text,
  route_id text,
  assigned_bus_id text,
  transport_status USER-DEFINED DEFAULT 'active'::transport_student_status,
  home_address text,
  latitude double precision,
  longitude double precision,
  rfid_tag text,
  qr_code text,
  default_boarding_time time without time zone,
  default_drop_time time without time zone,
  CONSTRAINT students_pkey PRIMARY KEY (id),
  CONSTRAINT students_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT students_pickup_stop_id_fkey FOREIGN KEY (pickup_stop_id) REFERENCES public.stops(id),
  CONSTRAINT students_drop_stop_id_fkey FOREIGN KEY (drop_stop_id) REFERENCES public.stops(id),
  CONSTRAINT students_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id),
  CONSTRAINT students_assigned_bus_id_fkey FOREIGN KEY (assigned_bus_id) REFERENCES public.buses(id)
);
CREATE TABLE public.trip_locations (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  trip_id text NOT NULL,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  speed double precision,
  heading double precision,
  accuracy double precision,
  recorded_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_locations_pkey PRIMARY KEY (id),
  CONSTRAINT trip_locations_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.trip_logs (
  id text NOT NULL DEFAULT md5(((random())::text || (clock_timestamp())::text)),
  school_id text NOT NULL,
  student_id text NOT NULL,
  bus_id text,
  driver_id text,
  boarding_time timestamp with time zone,
  drop_time timestamp with time zone,
  status USER-DEFINED NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_logs_pkey PRIMARY KEY (id),
  CONSTRAINT trip_logs_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT trip_logs_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT trip_logs_bus_id_fkey FOREIGN KEY (bus_id) REFERENCES public.buses(id),
  CONSTRAINT trip_logs_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.trip_stops (
  id text NOT NULL DEFAULT md5(((random())::text || (clock_timestamp())::text)),
  school_id text NOT NULL,
  trip_id text NOT NULL,
  student_id text,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  sequence integer NOT NULL,
  planned_eta timestamp with time zone,
  current_eta timestamp with time zone,
  stop_status text NOT NULL DEFAULT 'scheduled'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_stops_pkey PRIMARY KEY (id),
  CONSTRAINT trip_stops_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT trip_stops_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_stops_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id)
);
CREATE TABLE public.trip_students (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  trip_id text NOT NULL,
  student_id text NOT NULL,
  stop_id text,
  sequence integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'boarded'::text, 'dropped'::text, 'no_show'::text, 'skipped'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_students_pkey PRIMARY KEY (id),
  CONSTRAINT trip_students_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_students_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT trip_students_stop_id_fkey FOREIGN KEY (stop_id) REFERENCES public.stops(id)
);
CREATE TABLE public.trips (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  school_id text NOT NULL,
  route_id text,
  bus_id text,
  driver_id text,
  trip_date date NOT NULL DEFAULT CURRENT_DATE,
  direction text NOT NULL DEFAULT 'pickup'::text CHECK (direction = ANY (ARRAY['pickup'::text, 'drop'::text])),
  status text NOT NULL DEFAULT 'planned'::text CHECK (status = ANY (ARRAY['planned'::text, 'dispatched'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  scheduled_start timestamp with time zone,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id),
  CONSTRAINT trips_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id),
  CONSTRAINT trips_bus_id_fkey FOREIGN KEY (bus_id) REFERENCES public.buses(id),
  CONSTRAINT trips_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.users (
  id text NOT NULL DEFAULT (gen_random_uuid())::text,
  auth_user_id text NOT NULL UNIQUE,
  email text NOT NULL,
  full_name text NOT NULL,
  role text NOT NULL DEFAULT 'parent'::text CHECK (role = ANY (ARRAY['super_admin'::text, 'admin'::text, 'driver'::text, 'parent'::text])),
  school_id text,
  avatar_url text,
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  phone_number text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);